-- Выполните этот файл один раз в Supabase → SQL Editor.
-- Профиль создаётся автоматически при регистрации пользователя через Auth.
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null default '',
  phone text not null default '',
  visits_count integer not null default 0 check (visits_count >= 0),
  permission text check (permission is null or permission in ('operator', 'manager', 'organizator')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles
  add column if not exists visits_count integer not null default 0 check (visits_count >= 0);
alter table public.profiles
  add column if not exists permission text check (permission is null or permission in ('operator', 'manager', 'organizator'));

alter table public.profiles enable row level security;

grant select on public.profiles to authenticated;
revoke update on public.profiles from authenticated;
grant update (full_name) on public.profiles to authenticated;
revoke delete on public.profiles from authenticated;

create or replace function public.current_staff_permission()
returns text language sql stable security definer set search_path = ''
as $$ select permission from public.profiles where id = auth.uid() $$;

create table if not exists public.staff_bookings (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  quest_name text not null,
  booking_date date not null,
  booking_time time not null,
  client_name text not null,
  client_phone text not null,
  client_email text not null default '',
  players integer not null default 1,
  status text not null default 'confirmed',
  comment text not null default '',
  extra_services text not null default '',
  total_amount text not null default '',
  assigned_employee text not null default '',
  paid_amount numeric(12,2) not null default 0,
  prepayment_amount numeric(12,2) not null default 0,
  service_comment text not null default '',
  source text not null default 'site',
  erp_slot_id text not null default '',
  idempotency_key text unique,
  created_at timestamptz not null default now()
);
alter table public.staff_bookings enable row level security;
alter table public.staff_bookings add column if not exists user_id uuid references auth.users(id) on delete set null;
alter table public.staff_bookings add column if not exists extra_services text not null default '';
alter table public.staff_bookings add column if not exists total_amount text not null default '';
alter table public.staff_bookings add column if not exists assigned_employee text not null default '';
alter table public.staff_bookings add column if not exists paid_amount numeric(12,2) not null default 0;
alter table public.staff_bookings add column if not exists prepayment_amount numeric(12,2) not null default 0;
alter table public.staff_bookings add column if not exists service_comment text not null default '';
alter table public.staff_bookings add column if not exists source text not null default 'site';
alter table public.staff_bookings add column if not exists erp_slot_id text not null default '';
alter table public.staff_bookings add column if not exists idempotency_key text unique;
grant insert on public.staff_bookings to anon;
grant select, insert, update, delete on public.staff_bookings to authenticated;
grant usage, select on sequence public.staff_bookings_id_seq to authenticated;
grant usage, select on sequence public.staff_bookings_id_seq to anon;
drop policy if exists "Users can create own bookings" on public.staff_bookings;
create policy "Users can create own bookings" on public.staff_bookings for insert
  with check (user_id is null or auth.uid() = user_id);
drop policy if exists "Staff can view bookings" on public.staff_bookings;
create policy "Staff can view bookings" on public.staff_bookings for select
  using (public.current_staff_permission() in ('operator', 'manager', 'organizator'));
drop policy if exists "Managers can update bookings" on public.staff_bookings;
create policy "Managers can update bookings" on public.staff_bookings for update
  using (public.current_staff_permission() in ('manager', 'organizator'))
  with check (public.current_staff_permission() in ('manager', 'organizator'));
drop policy if exists "Managers can delete bookings" on public.staff_bookings;
create policy "Managers can delete bookings" on public.staff_bookings for delete
  using (public.current_staff_permission() in ('manager', 'organizator'));

-- Отдельный список клиентов сотрудников. Запись создаётся вместе с бронью
-- функцией create_site_booking, поэтому частично сохранённых данных не бывает.
create table if not exists public.staff_clients (
  id bigint generated by default as identity primary key,
  booking_id bigint not null unique references public.staff_bookings(id) on delete cascade,
  client_name text not null,
  client_phone text not null,
  client_email text not null default '',
  quest_name text not null,
  booking_date date not null,
  booking_time time not null,
  comment text not null default '',
  extra_services text not null default '',
  created_at timestamptz not null default now()
);
alter table public.staff_clients enable row level security;
alter table public.staff_clients add column if not exists comment text not null default '';
grant select, update, delete on public.staff_clients to authenticated;
drop policy if exists "Managers can view booking clients" on public.staff_clients;
create policy "Managers can view booking clients" on public.staff_clients for select
  using (public.current_staff_permission() in ('manager', 'organizator'));
drop policy if exists "Organizators can update booking clients" on public.staff_clients;
create policy "Organizators can update booking clients" on public.staff_clients for update
  using (public.current_staff_permission() = 'organizator')
  with check (public.current_staff_permission() = 'organizator');
drop policy if exists "Organizators can delete booking clients" on public.staff_clients;
create policy "Organizators can delete booking clients" on public.staff_clients for delete
  using (public.current_staff_permission() = 'organizator');

-- Сохраняет видимость броней, созданных до появления отдельной таблицы клиентов.
insert into public.staff_clients (
  booking_id, client_name, client_phone, client_email, quest_name,
  booking_date, booking_time, comment, extra_services, created_at
)
select id, client_name, client_phone, client_email, quest_name,
       booking_date, booking_time, comment, extra_services, created_at
from public.staff_bookings
on conflict on constraint staff_clients_booking_id_key do nothing;

update public.staff_clients as client
set comment = booking.comment
from public.staff_bookings as booking
where client.booking_id = booking.id
  and client.comment = ''
  and booking.comment <> '';

create or replace function public.create_site_booking(p_booking jsonb, p_idempotency_key text)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_booking_id bigint;
  supplied_user_id uuid := nullif(p_booking ->> 'user_id', '')::uuid;
begin
  if coalesce(trim(p_booking ->> 'client_name'), '') = ''
     or coalesce(trim(p_booking ->> 'client_phone'), '') = '' then
    raise exception 'Имя и телефон обязательны';
  end if;
  if supplied_user_id is not null and supplied_user_id is distinct from auth.uid() then
    raise exception 'Нельзя создать бронь от имени другого пользователя';
  end if;

  if coalesce(trim(p_idempotency_key), '') = ''
     or coalesce(trim(p_booking ->> 'quest_name'), '') = '' then
    raise exception 'Не передан идентификатор запроса или название квеста';
  end if;

  insert into public.staff_bookings (
    user_id, quest_name, booking_date, booking_time, client_name, client_phone,
    client_email, players, status, comment, extra_services, total_amount,
    source, idempotency_key
  ) values (
    supplied_user_id, trim(p_booking ->> 'quest_name'), (p_booking ->> 'booking_date')::date,
    (p_booking ->> 'booking_time')::time, trim(p_booking ->> 'client_name'),
    trim(p_booking ->> 'client_phone'), coalesce(trim(p_booking ->> 'client_email'), ''),
    greatest(coalesce((p_booking ->> 'players')::integer, 1), 1), 'new',
    coalesce(p_booking ->> 'comment', ''), coalesce(p_booking ->> 'extra_services', ''),
    coalesce(p_booking ->> 'total_amount', ''), 'site', p_idempotency_key
  )
  on conflict (idempotency_key) do update
    set idempotency_key = excluded.idempotency_key
  returning id into v_booking_id;

  insert into public.staff_clients (
    booking_id, client_name, client_phone, client_email, quest_name,
    booking_date, booking_time, comment, extra_services
  ) values (
    v_booking_id, trim(p_booking ->> 'client_name'), trim(p_booking ->> 'client_phone'),
    coalesce(trim(p_booking ->> 'client_email'), ''), trim(p_booking ->> 'quest_name'),
    (p_booking ->> 'booking_date')::date, (p_booking ->> 'booking_time')::time,
    coalesce(p_booking ->> 'comment', ''),
    coalesce(p_booking ->> 'extra_services', '')
  )
  on conflict on constraint staff_clients_booking_id_key do nothing;
  return v_booking_id;
end;
$$;
revoke all on function public.create_site_booking(jsonb, text) from public;
grant execute on function public.create_site_booking(jsonb, text) to anon, authenticated;

-- Оператор может менять только статус и сумму в поле «Оплачено».
create or replace function public.operator_update_booking(
  p_booking_id bigint,
  p_status text,
  p_paid_amount numeric
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if public.current_staff_permission() <> 'operator' then
    raise exception 'Функция доступна только оператору';
  end if;
  if p_status not in ('new', 'service', 'confirmed', 'visited', 'no_answer', 'awaiting_prepayment', 'closed') then
    raise exception 'Недопустимый статус брони';
  end if;
  if p_paid_amount < 0 then
    raise exception 'Оплаченная сумма не может быть отрицательной';
  end if;
  update public.staff_bookings
  set status = p_status, paid_amount = p_paid_amount
  where id = p_booking_id;
  if not found then raise exception 'Бронь не найдена'; end if;
end;
$$;
revoke all on function public.operator_update_booking(bigint, text, numeric) from public;
grant execute on function public.operator_update_booking(bigint, text, numeric) to authenticated;

drop policy if exists "Managers can view clients" on public.profiles;
drop policy if exists "Staff can view employees" on public.profiles;
create policy "Staff can view employees" on public.profiles for select
  using (permission is not null and public.current_staff_permission() in ('manager', 'organizator'));
drop policy if exists "Organizator can update clients" on public.profiles;
drop policy if exists "Organizator can delete clients" on public.profiles;
drop function if exists public.organizator_update_client(uuid, text, text, integer);

drop policy if exists "Users can read own profile" on public.profiles;
create policy "Users can read own profile"
  on public.profiles for select
  using (auth.uid() = id);

drop policy if exists "Users can update own profile" on public.profiles;
create policy "Users can update own profile"
  on public.profiles for update
  using (auth.uid() = id)
  with check (auth.uid() = id);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = ''
as $$
begin
  insert into public.profiles (id, full_name, phone)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'full_name', ''),
    coalesce(new.raw_user_meta_data ->> 'phone', '')
  )
  on conflict (id) do update set
    full_name = excluded.full_name,
    phone = excluded.phone,
    updated_at = now();
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert or update of raw_user_meta_data on auth.users
  for each row execute procedure public.handle_new_user();

-- Переносит имя и телефон пользователей, созданных до установки триггера.
insert into public.profiles (id, full_name, phone)
select
  id,
  coalesce(raw_user_meta_data ->> 'full_name', ''),
  coalesce(raw_user_meta_data ->> 'phone', '')
from auth.users
on conflict (id) do update set
  full_name = excluded.full_name,
  phone = excluded.phone,
  updated_at = now();
